name: e_hadis40
version: 1.5.0+6
publish_to: "none"

description: Platform Pengajaran dan Pembelajaran Interaktif Modul Penghayatan Hadis 40 Imam al-Nawawi Kementerian Pendidikan Malaysia.

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.6
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/audio/
    - assets/fonts/
  fonts:
    - family: LotusLinotype
      fonts:
        - asset: assets/fonts/LotusLinotype.ttf
